Setup rubygems plumbing

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -4,7 +4,12 @@ IFS=$'\n\t'
 set -e
 
 if ! command -v cargo >/dev/null; then
-  echo "ERROR: Rust is not installed. Please install Rust and try again (https:///rustup.rs)."
+  echo "ERROR: Rust is not installed, please install and try again (https:///rustup.rs)."
+  exit 1
+fi
+
+if ! command -v b3sum >/dev/null; then
+  echo "ERROR: b3sum is not installed, please install and try again"
   exit 1
 fi
 
